### ISSUE TITLE
Error is coming for node js version 14 . node-pre-gyp ERR! node -v v12.22.1 node-pre-gyp ERR!

### ISSUE THREAD

**Issue by Rahul-012** [monobasic/Angular-Reactive-Demo-Shop#116]
Hi ,
Below error is coming when we  fire command npm install
node : version :14
npm version  :  6.17 t

Error: 
node-pre-gyp ERR! node -v v12.22.1

I am using alpine 3.17

**Comment by Rahul-012** [comment]
![image](https://user-images.githubusercontent.com/17723293/123513953-a7553e80-d6ad-11eb-8b30-bb9545a00a7a.png)

**Comment by Faouzii** [comment]
Did you solve the problem ?
